### ISSUE TITLE
Hue Light Node in knxUltimate palette

### ISSUE THREAD

**Issue by rue67** [Supergiovane/node-red-contrib-knx-ultimate#259]
Hello Max,

we had recently some conversation in knx-user-forum.de regarding KnxUltimateHueLight-Node.
You wanted me to report here my findings.

---------

I  found out some improper behaviour:

When check box "Link brightness to on/off switch" is unselected, after switching off-on the lamp
brightness still isn't properly restored to it's previous value, it is set to minimum resp. off then.

When check box "Link brightness to on/off switch" is selected, brighness is properly set to
100% after off/on.

----------

My testbench:

Platform Rasperry Pi Model 3B
with headless Debian bullseye (ver. 11)
Kernel 6.1

Node-Red:
3.0.2
node-red-contrib-knx-ultimate
2.1.34 / 2.1.39
node-red-dashboard
3.5.0
node-red-node-pi-gpio
2.0.6

Philips Hue-Bridge
(square version)

Philips Hue white ambiance lamp 8.5W
(tuneable white)

**Comment by Supergiovane** [comment]
Fixed in v 2.1.41

**Comment by rue67** [comment]
HI Massimo,

I won't be annoying but off/on with checkbox "link brightness to on/off switch" OFF still doesn't work properly.

I have now installend knxUltimate 2.1.41 together with the latest HueEngine/Hue_config.
KNX, NodeRed-dashboard control and original Hue-App on mobile phone are working together.
This is working fine - when changing Brightness/Color-Temp at one control the others
follow with correct status, except the on/off.

When the lamp is switched off/on with KNX and dashboard the brighness setting still isn't restored
to it's previous value, it starts with 0 after on.
I had I look with the ETS group monitor, the 0 does not come from KNX.

With the Hue-App on mobile phone this works well, brightness is set to the value before switching off.

**Comment by rue67** [comment]
[
    {
        "id": "c8fb0b5fbc227668",
        "type": "group",
        "z": "d2436d45d1769fc5",
        "style": {
            "stroke": "#999999",
            "stroke-opacity": "1",
            "fill": "none",
            "fill-opacity": "1",
            "label": true,
            "label-position": "nw",
            "color": "#a4a4a4"
        },
        "nodes": [
            "b743011c552e0548",
            "c563d8c55c7937d3",
            "664f026c92a158cb",
            "1e6ea378a3c3b62c",
            "a517c8b028788b80",
            "46b0f7ee71633af3",
            "87282a47fded1d62",
            "083486f1d60f299b",
            "050adb302baef0a0",
            "1b2265c9434699e3",
            "68ab5c43d3fd05c5",
            "cd6f44d9764f5ee8",
            "75f106b5a1dede5b",
            "7e4dff91e92f2564",
            "9191fb3dc38355e9",
            "8d9ff1cd282b773a",
            "ca5ee4ab1f36188a",
            "917d982d19510ff5",
            "fba890fc3f65b99b",
            "698ad43f2d94b50d",
            "51f363385af0f3f0",
            "8c390973031ff5d6",
            "38c5f24b642a8e18",
            "648c033e0c91583c",
            "3b859c56a37f4421",
            "b8d59263fcf67931",
            "9bb372a6ae5222bb",
            "3fc531b57533a962",
            "2bd53b1515c83d60",
            "341a2b9f663f0287"
        ],
        "x": 34,
        "y": 1919,
        "w": 1092,
        "h": 962
    },
    {
        "id": "b743011c552e0548",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "HUE 2",
        "payload": "false",
        "payloadType": "bool",
        "x": 630,
        "y": 2140,
        "wires": [
            [
                "c563d8c55c7937d3"
            ]
        ]
    },
    {
        "id": "c563d8c55c7937d3",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/8",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 Switch",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 890,
        "y": 2040,
        "wires": [
            []
        ]
    },
    {
        "id": "664f026c92a158cb",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/9",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 status",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 370,
        "y": 2040,
        "wires": [
            [
                "68ab5c43d3fd05c5",
                "1e6ea378a3c3b62c"
            ]
        ]
    },
    {
        "id": "1e6ea378a3c3b62c",
        "type": "ui_switch",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "Schalter HUE2",
        "label": "Schalter HUE2",
        "tooltip": "",
        "group": "5b5f9a44eca4335b",
        "order": 5,
        "width": 7,
        "height": 1,
        "passthru": false,
        "decouple": "true",
        "topic": "HUE 2 Schalter",
        "topicType": "str",
        "style": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "onicon": "",
        "oncolor": "",
        "offvalue": "false",
        "offvalueType": "bool",
        "officon": "",
        "offcolor": "",
        "animate": false,
        "className": "",
        "x": 640,
        "y": 2040,
        "wires": [
            [
                "c563d8c55c7937d3"
            ]
        ],
        "inputLabels": [
            "ein"
        ],
        "outputLabels": [
            "aus"
        ],
        "icon": "node-red/light.svg"
    },
    {
        "id": "a517c8b028788b80",
        "type": "ui_slider",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "CT slider",
        "label": "Farbtemperatur",
        "tooltip": "",
        "group": "5b5f9a44eca4335b",
        "order": 6,
        "width": 0,
        "height": 0,
        "passthru": false,
        "outs": "end",
        "topic": "topic",
        "topicType": "msg",
        "min": "2200",
        "max": "6500",
        "step": "43",
        "className": "",
        "x": 680,
        "y": 2520,
        "wires": [
            [
                "1b2265c9434699e3"
            ]
        ]
    },
    {
        "id": "46b0f7ee71633af3",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "HUE 2",
        "payload": "true",
        "payloadType": "bool",
        "x": 620,
        "y": 2100,
        "wires": [
            [
                "c563d8c55c7937d3"
            ]
        ]
    },
    {
        "id": "87282a47fded1d62",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/1",
        "outputtopic": "status_ct",
        "dpt": "5.001",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 Status CT",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 320,
        "y": 2520,
        "wires": [
            [
                "cd6f44d9764f5ee8",
                "51f363385af0f3f0"
            ]
        ]
    },
    {
        "id": "083486f1d60f299b",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/3",
        "outputtopic": "",
        "dpt": "6.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 Value Brightness relative",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 950,
        "y": 2300,
        "wires": [
            []
        ]
    },
    {
        "id": "050adb302baef0a0",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/5",
        "outputtopic": "status_v",
        "dpt": "5.001",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 Status Brightness",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": "1",
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": "2",
        "passthrough": "yes",
        "x": 410,
        "y": 2220,
        "wires": [
            [
                "8d9ff1cd282b773a",
                "917d982d19510ff5"
            ]
        ]
    },
    {
        "id": "1b2265c9434699e3",
        "type": "function",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "K->%",
        "func": "return [\n    { payload : Math.round((msg.payload-2200)/43) }     // scale value from 2200-6500 to 0-100\n];",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 830,
        "y": 2520,
        "wires": [
            [
                "fba890fc3f65b99b"
            ]
        ]
    },
    {
        "id": "68ab5c43d3fd05c5",
        "type": "debug",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "debug 15",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 620,
        "y": 2000,
        "wires": []
    },
    {
        "id": "cd6f44d9764f5ee8",
        "type": "debug",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "debug 17",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 660,
        "y": 2440,
        "wires": []
    },
    {
        "id": "75f106b5a1dede5b",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "darker",
        "payload": "6",
        "payloadType": "num",
        "x": 680,
        "y": 2280,
        "wires": [
            [
                "083486f1d60f299b"
            ]
        ]
    },
    {
        "id": "7e4dff91e92f2564",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "stopp",
        "payload": "0",
        "payloadType": "num",
        "x": 670,
        "y": 2320,
        "wires": [
            [
                "083486f1d60f299b"
            ]
        ]
    },
    {
        "id": "9191fb3dc38355e9",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "brighter",
        "payload": "-6",
        "payloadType": "num",
        "x": 680,
        "y": 2360,
        "wires": [
            [
                "083486f1d60f299b"
            ]
        ]
    },
    {
        "id": "8d9ff1cd282b773a",
        "type": "ui_slider",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "Brightness Slider ",
        "label": "Helligkeit",
        "tooltip": "",
        "group": "5b5f9a44eca4335b",
        "order": 7,
        "width": 0,
        "height": 0,
        "passthru": false,
        "outs": "end",
        "topic": "topic",
        "topicType": "msg",
        "min": 0,
        "max": "100",
        "step": 1,
        "className": "",
        "x": 650,
        "y": 2220,
        "wires": [
            [
                "ca5ee4ab1f36188a"
            ]
        ]
    },
    {
        "id": "ca5ee4ab1f36188a",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/6",
        "outputtopic": "",
        "dpt": "5.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE2 Value Brightness",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 930,
        "y": 2220,
        "wires": [
            []
        ]
    },
    {
        "id": "917d982d19510ff5",
        "type": "debug",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "debug 25",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 640,
        "y": 2180,
        "wires": []
    },
    {
        "id": "fba890fc3f65b99b",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/7",
        "outputtopic": "",
        "dpt": "5.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE Value CT ",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 1020,
        "y": 2520,
        "wires": [
            []
        ]
    },
    {
        "id": "698ad43f2d94b50d",
        "type": "knxUltimateHueLight",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "serverHue": "f92b5f731182c28d",
        "name": "Light: Hue ambiance lamp 2 - Room: Büro",
        "nameLightSwitch": "",
        "GALightSwitch": "2/2/8",
        "dptLightSwitch": "1.001",
        "nameLightState": "",
        "GALightState": "2/2/9",
        "dptLightState": "1.001",
        "nameLightDIM": "",
        "GALightDIM": "2/2/3",
        "dptLightDIM": "3.007",
        "nameLightColor": "",
        "GALightColor": "",
        "dptLightColor": "232.600",
        "nameLightColorState": "",
        "GALightColorState": "",
        "dptLightColorState": "232.600",
        "nameLightHSV": "",
        "GALightHSV": "2/2/0",
        "dptLightHSV": "3.007",
        "nameLightHSVPercentage": "",
        "GALightHSVPercentage": "2/2/7",
        "dptLightHSVPercentage": "5.001",
        "nameLightHSVState": "",
        "GALightHSVState": "2/2/1",
        "dptLightHSVState": "5.001",
        "nameLightBrightness": "",
        "GALightBrightness": "2/2/6",
        "dptLightBrightness": "5.001",
        "nameLightBrightnessState": "",
        "GALightBrightnessState": "2/2/5",
        "dptLightBrightnessState": "5.001",
        "nameLightBlink": "",
        "GALightBlink": "",
        "dptLightBlink": "1.001",
        "nameLightColorCycle": "",
        "GALightColorCycle": "",
        "dptLightColorCycle": "1.001",
        "enableDayNightLighting": false,
        "colorAtSwitchOnDayTime": "{\"red\":255, \"green\":255, \"blue\":255}",
        "colorAtSwitchOnNightTime": "{\"red\":23, \"green\":4, \"blue\":0}",
        "invertDayNight": false,
        "nameDaylightSensor": "",
        "GADaylightSensor": "",
        "dptDaylightSensor": "1.001",
        "linkBrightnessToSwitchStatus": "no",
        "hueDevice": "30e5b55e-2292-4409-a8ae-8b54f84b9a79#light",
        "x": 220,
        "y": 1960,
        "wires": []
    },
    {
        "id": "51f363385af0f3f0",
        "type": "function",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "%->K",
        "func": "return [\n    { payload : Math.round(msg.payload*43+2200) }     // scale value from 0-100% to 2200-6500K\n];",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 530,
        "y": 2520,
        "wires": [
            [
                "a517c8b028788b80"
            ]
        ]
    },
    {
        "id": "8c390973031ff5d6",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/0",
        "outputtopic": "",
        "dpt": "6.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HUE Value CT relative",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 940,
        "y": 2580,
        "wires": [
            []
        ]
    },
    {
        "id": "38c5f24b642a8e18",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/4",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "GTS2 dim direction",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 430,
        "y": 2740,
        "wires": [
            [
                "9bb372a6ae5222bb"
            ]
        ]
    },
    {
        "id": "648c033e0c91583c",
        "type": "knxUltimate",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "server": "1063466374f07a5e",
        "topic": "2/2/2",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "GTS2 Switch/dim",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 910,
        "y": 2740,
        "wires": [
            []
        ]
    },
    {
        "id": "3b859c56a37f4421",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "HUE 2",
        "payload": "true",
        "payloadType": "bool",
        "x": 640,
        "y": 2800,
        "wires": [
            [
                "648c033e0c91583c"
            ]
        ]
    },
    {
        "id": "b8d59263fcf67931",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "HUE 2",
        "payload": "false",
        "payloadType": "bool",
        "x": 650,
        "y": 2840,
        "wires": [
            [
                "648c033e0c91583c"
            ]
        ]
    },
    {
        "id": "9bb372a6ae5222bb",
        "type": "debug",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "debug 18",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 640,
        "y": 2740,
        "wires": []
    },
    {
        "id": "3fc531b57533a962",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "colder",
        "payload": "3",
        "payloadType": "num",
        "x": 680,
        "y": 2580,
        "wires": [
            [
                "8c390973031ff5d6"
            ]
        ]
    },
    {
        "id": "2bd53b1515c83d60",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "stopp",
        "payload": "0",
        "payloadType": "num",
        "x": 670,
        "y": 2620,
        "wires": [
            [
                "8c390973031ff5d6"
            ]
        ]
    },
    {
        "id": "341a2b9f663f0287",
        "type": "inject",
        "z": "d2436d45d1769fc5",
        "g": "c8fb0b5fbc227668",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "warmer",
        "payload": "-3",
        "payloadType": "num",
        "x": 680,
        "y": 2660,
        "wires": [
            [
                "8c390973031ff5d6"
            ]
        ]
    },
    {
        "id": "1063466374f07a5e",
        "type": "knxUltimate-config",
        "host": "192.168.178.28",
        "port": "3671",
        "physAddr": "1.1.7",
        "hostProtocol": "TunnelUDP",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error",
        "name": "KNX Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "50",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "autoReconnect": "yes"
    },
    {
        "id": "5b5f9a44eca4335b",
        "type": "ui_group",
        "name": "Test LED",
        "tab": "dbc8cbc0cec0695b",
        "order": 2,
        "disp": true,
        "width": 7,
        "collapse": false,
        "className": ""
    },
    {
        "id": "f92b5f731182c28d",
        "type": "hue-config",
        "host": "192.168.178.30",
        "name": "Philips hue",
        "bridgeid": "ECB5FAFFFE206117"
    },
    {
        "id": "dbc8cbc0cec0695b",
        "type": "ui_tab",
        "name": "Home",
        "icon": "dashboard",
        "order": 2,
        "disabled": false,
        "hidden": false
    }
]

**Comment by Supergiovane** [comment]
Hi

**Comment by Supergiovane** [comment]
Hi
i need you to delete the content of this field, then try again controlling the light via KNX commands and let me know.
<img width="617" alt="Node-RED" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/458e72a1-7429-4dd2-847c-039ee7066c36">

**Comment by Supergiovane** [comment]
Hi,
even with the fiels indicated by the arrow, i cannot reproduce the issue.
I need you, please, to follow the BUG guidelines, step by step, thanks:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by Supergiovane** [comment]
Nevermind, i've maybe understood the issue.
Please upgrade to 2.1.43.
Please next time, follow the BUG report rules, so i can better understand the issue. Thanks.

**Comment by rue67** [comment]
Hi, 
I have upgraded to 2.1.43, unfortunately still not working properly.

When I have more time I will set up a new pi with node-red and knx-ultimate from scratch and make a minimum flow with the Hue-lamp and some dashboard controls only.  I will come to you when I have new findings.

Thank a lot you for your time.

Ruediger
