### ISSUE TITLE
Night lighting menu

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#288]
After the last upgrade, in the behaviour section, I don't see the correct menu for "night lighting".
When I enter the tab it correctly shows "no night lighting", after a second it changes with the two option shown in the screenshot.
This affects some lights only.
I deleted cookies and cache but nothing changed.

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/347e937d-2956-4d14-a41d-95412187292f)

**Comment by Supergiovane** [comment]
Fixed in the upcoming version. It’s related to misunderstanding in the light capabilities sent from the hie bridge.

**Comment by evazzoler** [comment]
With the latest update the "no" item is now selectable, but still missing the "color".
It is a GU10 color lamp.

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/1bfc8b40-5010-4d61-8019-dae061327d73)

**Comment by Supergiovane** [comment]
Evidentemente, the GU10 don't expose the color property.
I don't have any GU10 to test, but i'll search on the internet and see what properties the GU10 exposes.

**Comment by Supergiovane** [comment]
Are they these ? https://www.philips-hue.com/it-it/p/hue-white-and-color-ambiance-gu10---faretto-connesso----confezione-da-2-/8719514340084#overview

**Comment by evazzoler** [comment]
> Are they these ? https://www.philips-hue.com/it-it/p/hue-white-and-color-ambiance-gu10---faretto-connesso----confezione-da-2-/8719514340084#overview

Yes, they are. But they remember the latest color when I turn them on, so it is managed by KNX ultimate.

**Comment by Supergiovane** [comment]
Hi
can you try again with version 2.2.29 ad let me know?

**Comment by evazzoler** [comment]
> Hi could you try again with version 2.2.29 ad let me know?

2.2.29 seems to fix it in my case. :-)
